=== wasim7raja10/portfolio/.astro/collections/experiences.schema.json
{
  "$ref": "#/definitions/experiences",
  "definitions": {
    "experiences": {
      "type": "object",
      "properties": {
        "company": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "description": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "image": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            },
            "alt": {
              "type": "string"
            }
          },
          "required": [
            "url",
            "alt"
          ],
          "additionalProperties": false
        },
        "startDate": {
          "type": "string"
        },
        "endDate": {
          "type": "string"
        },
        "skills": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "company",
        "role",
        "startDate"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== wasim7raja10/portfolio/src/content/experiences/clearcals.json
{
  "role": "Software Engineer",
  "company": "Clearcals",
  "startDate": "2022-07-14T18:30:00.000Z",
  "endDate": "2024-01-30T18:30:00.000Z",
  "description": [
    "Ownership of a enterprise application which is a one-stop CRM solution for dieticians.",
    "Ownership of a marketing website which includes product marketing information, blogs, etc."
  ],
  "skills": [
    "React",
    "RxJs",
    "Angular Material",
    "Angular",
    "Sass",
    "NgRx"
  ]
}

=== wasim7raja10/portfolio/src/content/experiences/instamart.json
{
  "role": "Software Engineer",
  "company": "Instamart.ai",
  "startDate": "2024-03-31T18:30:00.000Z",
  "endDate": "2024-08-30T18:30:00.000Z",
  "description": [
    "Developed the frontend for an AI-powered chatbot and its admin dashboard.",
    "The chatbot was designed to interact with users on the client’s website, while the admin dashboard provided a comprehensive interface for managing conversations, monitoring chatbot performance, and making adjustments to the chatbot’s responses."
  ],
  "skills": [
    "Javascript",
    "Tailwind CSS",
    "React.js"
  ]
}

=== wasim7raja10/portfolio/src/content/experiences/myrevue.json
{
  "role": "Frontend Developer Intern",
  "company": "MyRevue",
  "startDate": "2021-12-31T18:30:00.000Z",
  "endDate": "2022-03-30T18:30:00.000Z",
  "description": [
    "Designed and implemented an analytics dashboard, resulting in a 30% increase in tracking efficiency for sponsorship metrics, ad revenue, and product shipment details.",
    "Created dynamic components, including an infinite scrollable short video player similar to TikTok, boosting user engagement by 40%."
  ],
  "skills": [
    "Sanity CMS",
    "Firebase",
    "Tailwind",
    "Next.js",
    "React.js"
  ]
}
