=== wasim7raja10/portfolio/.astro/collections/projects.schema.json
{
  "$ref": "#/definitions/projects",
  "definitions": {
    "projects": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "image": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            },
            "alt": {
              "type": "string"
            }
          },
          "required": [
            "url",
            "alt"
          ],
          "additionalProperties": false
        },
        "skills": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "liveUrl": {
          "type": "string"
        },
        "githubUrl": {
          "type": "string"
        },
        "startDate": {
          "type": "string"
        },
        "endDate": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "startDate"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== wasim7raja10/portfolio/src/content/projects/codechef.json
{
  "name": "CodeChef BCET Chapter Wep App",
  "image": {
    "url": "/src/assets/images/projects/codechefbcetchapter.png",
    "alt": "CodeChef BCET Chapter homepage"
  },
  "startDate": "2023-07-31T18:30:00.000Z",
  "endDate": "2023-08-30T18:30:00.000Z",
  "description": [
    "Students can participate in events.",
    "Aim of this web app was to help students find Resources, Events, etc."
  ],
  "skills": ["Tailwind", "React", "Firebase"],
  "liveUrl": "https://codechefbcetchapter.netlify.app/",
  "githubUrl": "https://github.com/CodeChef-BCET-Chapter/ccbcet-website"
}

=== wasim7raja10/portfolio/src/content/projects/zappotech.json
{
  "name": "zappotech",
  "image": {
    "url": "/src/assets/images/projects/screenshot-1729520620300.png",
    "alt": "ZappoTech"
  },
  "startDate": "2023-12-31T18:30:00.000Z",
  "endDate": "2024-08-30T18:30:00.000Z",
  "skills": [
    "Tailwind CSS",
    "Supabase",
    "Algolia",
    "Next.js"
  ],
  "liveUrl": "https://zappotech.com/",
  "githubUrl": "https://github.com/wasim7raja10/blog-next-sanity"
}

=== wasim7raja10/portfolio/src/content/projects/myread.json
{
  "name": "My Read",
  "image": {
    "url": "/src/assets/images/projects/myread.png",
    "alt": "MyRead project homepage"
  },
  "startDate": "2022-11-06T18:30:00.000Z",
  "endDate": "2022-12-02T18:30:00.000Z",
  "description": [
    "Check book information.",
    "Add book from book database to the tracking list."
  ],
  "skills": ["CSS", "React"],
  "liveUrl": "https://readtrack.netlify.app/",
  "githubUrl": "https://github.com/wasim7raja10/nd0191-c1-myreads"
}

=== wasim7raja10/portfolio/src/content/projects/portfolio.json
{
  "name": "Portfolio",
  "image": {
    "url": "/src/assets/images/projects/portfolio astro.png",
    "alt": "Portfolio project homepage"
  },
  "startDate": "2024-06-30T18:30:00.000Z",
  "endDate": "2024-07-14T18:30:00.000Z",
  "description": [
    "It contains all my projects, experiences.",
    "List of blogs about various topics."
  ],
  "skills": [
    "Astro",
    "Tailwind CSS",
    "Tina CMS"
  ],
  "liveUrl": "https://wasimraja.netlify.app",
  "githubUrl": "https://github.com/wasim7raja10/portfolio"
}
